### ISSUE TITLE
Theme doesn't exist

### ISSUE THREAD

**Issue by msilberg** [manishprivet/dynamic-gnome-wallpapers#15]
**Describe the bug**
I have a default theme Adwaita-dark, which I was able to verify with this command:
gsettings get org.gnome.desktop.interface gtk-theme

And also by listing my themes category:
ls -l /usr/share/themes
total 24
drwxr-xr-x 4 root root 4096 Sep 28 00:45 Adwaita
drwxr-xr-x 4 root root 4096 Sep 28 00:45 Adwaita-dark
drwxr-xr-x 4 root root 4096 Sep 28 00:47 Default
drwxr-xr-x 4 root root 4096 Sep 28 00:47 Emacs
drwxr-xr-x 4 root root 4096 Sep 28 00:47 HighContrast
drwxr-xr-x 3 root root 4096 Sep 28 00:47 Raleigh

However the installation script won't accept it anyway and always throws an error telling me that:
Adwaita-dark theme doesn't exist. Make sure you spelled it correctly.

**To Reproduce**
1. run insallation script:
curl -s https://wallpapers.manishk.dev/install.sh | bash -s Adwaita-dark
2. See error

**Expected behavior**
Installation script should finish its run.

**Screenshots**
![image](https://github.com/user-attachments/assets/89491f4e-fc3a-4e5b-929e-1732462bfdaf)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - DE: Gnome 43.9

**Comment by neitsab** [comment]
It's just that Adwaita-dark isn't one of the supported theme codes. I know that it's written under the Installation heading:

> Replace THEME_CODE with the theme code of your choice.

But this "choice" needs to be made between the 12 or so themes listed under the "[Wallpaper Gallery](https://github.com/manishprivet/dynamic-gnome-wallpapers#wallpaper-gallery)" heading. You can't put any theme name you'd like and expect the script to serve something to you, it's not designed to do that.

Hope it clears up the misunderstanding!
Cheers

**Comment by msilberg** [comment]
Ah, thanks for clarification.
I'd still suggest to update the Readme file by changing THEME_CODE to WALLPAPER_NAME, which IMO would be much more intuitive.
Best,
